### ISSUE TITLE
[Bug] Chart View not Working

### ISSUE THREAD

**Issue by serahkiburu** [routetopa/tet#1]
I was demo'ing TET yesterday, and realised chart view does not display visualisations, even with the example dataset from the latest TET video.

**Comment by arekstasiewicz** [comment]
Could you please provide link to the dataset?
Which browser are you using?

**Comment by serahkiburu** [comment]
@arekstasiewicz I am on Safari. [This is the dataset](http://vmegov01.deri.ie/en/dataset/d13cc82e-273c-408e-bb2c-9f24861b5d44).

**Comment by arekstasiewicz** [comment]
@callmealien I confirm that there is a bug with Safari browser - webcomponents.js causing the issue - we will investigate it

**Comment by arekstasiewicz** [comment]
`TypeError: wrap is not a function. (In 'wrap(e["import"])', 'wrap' is an instance of HTMLDivElement)`

**Comment by arekstasiewicz** [comment]
`Refused to get unsafe header "Location"`

Solution is to:
Only simple response headers are exposed when using CORS. Simple response headers are defined here.  Location is not a simple response headers. If we want to expose non-simple headers, we need to set the Access-Control-Expose-Headers header:

Access-Control-Expose-Headers: Location

**Comment by lucavicidomini** [comment]
Hi, another guy here suggests to import the polyfills. The chart is missing of Firefox for Windows, too.

**Comment by arekstasiewicz** [comment]
Fixed
