### ISSUE TITLE
Hyperlink Support in dataset description box 

### ISSUE THREAD

**Issue by serahkiburu** [routetopa/tet#118]
Hyperlinks in the description box not clickable at the moment, see data description box on [CKAN](https://data.openstate.eu/dataset/register-van-gevestigd-apothekers) vs [TET](https://tet.openstate.eu/en/dataset/5771d5ff-3118-4a68-8a2b-989506c23266)

**Comment by arekstasiewicz** [comment]
hello @callmealien - this is linked to #99
