### ISSUE TITLE
Data Quality measurement table

### ISSUE THREAD

**Issue by arekstasiewicz** [routetopa/tet#124]
- Name the graphical visual column - "Indicator"
- For “License” and “Version”, swap positions of graphics with texts to match the first two - “Metadata” and “content”
- Reposition the measure (e.g. “11 months, 3 weeks”) for “Last Update” to align with the column arrangement - _align left_

![screenshot 2017-11-02 12 54 27_preview](https://user-images.githubusercontent.com/2188771/32327046-067ee4a2-bfcd-11e7-9316-2155a44f7281.png)

**Comment by MaciejJanowski** [comment]
#124 issue closed
