### ISSUE TITLE
Links on related datasets do not work

### ISSUE THREAD

**Issue by serahkiburu** [routetopa/tet#14]
On clicking any dataset under the 'Related Dataset' feature, it gives the error below: 

**_Server Error:
Reasons
'records'_**

**Comment by arekstasiewicz** [comment]
@callmealien could you please provide link to the broken dataset page? It seems that one of the services is offline.

**Comment by serahkiburu** [comment]
@arekstasiewicz one such error page. http://vmegov01.deri.ie/en/dataset/ac281750-1615-4cf4-9e27-fd4c0845b78c

**Comment by arekstasiewicz** [comment]
@callmealien the same dataset is available at [Dublin Pilot website](http://dublin-tet.routetopa.eu/en/dataset/ac281750-1615-4cf4-9e27-fd4c0845b78c) - vmegov01 is our dev server.
