### ISSUE TITLE
Files section, number 3 is always added at the bottom

### ISSUE THREAD

**Issue by mogaio** [routetopa/tet#16]
In the Files section the number 3 is always added at the bottom
http://dublin-tet.routetopa.eu/en/dataset/58969481-417e-4f5a-b8ea-18b56419d0ed

**Comment by arekstasiewicz** [comment]
Seems like an error at pilot server. Will be fixed with next update.

![image](https://cloud.githubusercontent.com/assets/2188771/22647028/28e2a810-ec67-11e6-98da-e829538e5b2a.png)
