### ISSUE TITLE
dataset search result page, title of each file in it's tooltip 

### ISSUE THREAD

**Issue by mogaio** [routetopa/tet#17]
In the search result page, I guess we need to add title of each file in it's tooltip instead of view raw data to differentiate between the files from the same type
http://dublin-tet.routetopa.eu/en/search/?query=cost

**Comment by arekstasiewicz** [comment]
fixed: title of the resource is now displayed

![image](https://cloud.githubusercontent.com/assets/2188771/22646799/1c4d83b4-ec66-11e6-8e38-025921ee63d7.png)
