### ISSUE TITLE
TET platform

### ISSUE THREAD

**Issue by eosagie** [routetopa/tet#2]
1. Very faint search box borders. Needs to use a coloured border with improved brightness
2. Insert the ROUTE-TO-PA logo to match the one in the SPOD interface
3. The share icons lack tool-tips
4. Discussion button:
5. This section will keep scrolling down with contents as they develop over time
6. So, better to put it under the headings: 
   (a) Related datasets, 
   (b) Files 
7. and by the way, I suggest you use the words 'File format' instead of just 'Files'. Just a suggestion
8. currently, the discussion content is not collapsible - permanently in drop-down mode.
9. TET struggles a bit to open up in Internet Explorer browser

**Comment by arekstasiewicz** [comment]
I will create separate 'issues' for the reported elements.
