### ISSUE TITLE
Merge Datasets feature

### ISSUE THREAD

**Issue by serahkiburu** [routetopa/tet#21]
I can't find any two or more datasets that merge without conflict. Please share an example that works for this feature? Thank you

**Comment by arekstasiewicz** [comment]
Please have a look at [Prato example](http://prato-tet.routetopa.eu/en/search/?query=Atti+Comunali). The data structure must be similar, which is usually the case for the same publisher in linked datasets.

![image](https://cloud.githubusercontent.com/assets/2188771/22689836/a2dd5eb2-ed2a-11e6-8293-169f263fb11f.png)

![image](https://cloud.githubusercontent.com/assets/2188771/22689837/a65c88f6-ed2a-11e6-8c60-a1a039235a44.png)

**Comment by serahkiburu** [comment]
Thank you @arekstasiewicz . Adding this to the draft blogpost i am writing. I will link it here once it has been published.

**Comment by arekstasiewicz** [comment]
@callmealien thanks, great to hear that!

**Comment by serahkiburu** [comment]
@arekstasiewicz Blogpost is now up 
[7 ways the RouteToPA project has improved data sharing through CKAN](http://bit.ly/2muJMzn)

**Comment by arekstasiewicz** [comment]
@callmealien good work, thanks!
