### ISSUE TITLE
Dataset quality box

### ISSUE THREAD

**Issue by eosagie** [routetopa/tet#23]
[http://dublin-tet.routetopa.eu/en/dataset/d13cc82e-273c-408e-bb2c-9f24861b5d44](http://dublin-tet.routetopa.eu/en/dataset/d13cc82e-273c-408e-bb2c-9f24861b5d44)

Express 'Last updated' value in months instead of in days because number of days will become a very large value in future and may require user need to convert to months for better of timing.

**Comment by arekstasiewicz** [comment]
![image](https://cloud.githubusercontent.com/assets/2188771/23270292/49763bf0-f9eb-11e6-9c22-80a6e8914685.png)
