### ISSUE TITLE
RTPA - "Share this Page"

### ISSUE THREAD

**Issue by eosagie** [routetopa/tet#24]
The G lack the + in the G+ icon.
All icons lack tooltips

[http://dublin-tet.routetopa.eu/en/dataset/58fe3c27-04d6-49bb-8ade-ce94b649b5ed](http://dublin-tet.routetopa.eu/en/dataset/58fe3c27-04d6-49bb-8ade-ce94b649b5ed)

**Comment by arekstasiewicz** [comment]
![image](https://cloud.githubusercontent.com/assets/2188771/23265676/41b9660c-f9dd-11e6-8a37-6d27da2e4b47.png)
