### ISSUE TITLE
"View Summary" of dataset information

### ISSUE THREAD

**Issue by eosagie** [routetopa/tet#25]
As it relates to this dataset: Local Area Plans - 2011-2017 Development Plan - Dublin City Council
[http://dublin-tet.routetopa.eu/en/dataset/58fe3c27-04d6-49bb-8ade-ce94b649b5ed#](http://dublin-tet.routetopa.eu/en/dataset/58fe3c27-04d6-49bb-8ade-ce94b649b5ed)

If the selected dataset has not summary info to display, (unlike a few other datasets e.g.**) could this button explain so as in the case where no pdf is available?

Make changes only if you feel this is relevant.

** Dublin City Council Spending and Revenue budget
[http://dublin-tet.routetopa.eu/en/dataset/e28e9fb7-562c-40ee-8513-5f9df06aeaa7/summary](http://dublin-tet.routetopa.eu/en/dataset/e28e9fb7-562c-40ee-8513-5f9df06aeaa7/summary)

**Comment by arekstasiewicz** [comment]
fixed
