### ISSUE TITLE
File Download Buttons

### ISSUE THREAD

**Issue by eosagie** [routetopa/tet#33]
<img width="412" alt="greyed out buttons in red circle" src="https://cloud.githubusercontent.com/assets/22979549/22936990/190620ca-f2cf-11e6-8cdf-d63e08fce4c1.PNG">

These buttons should made brighter as they are active whereas they seem greyed out.
[http://dublin-tet.routetopa.eu/en/search/?query=](url)

**Comment by arekstasiewicz** [comment]
I have decreased the opacity - the idea is not to make the files stand out

![image](https://cloud.githubusercontent.com/assets/2188771/23267480/cbf50cfe-f9e2-11e6-84b3-2a1e3a1e67a8.png)
