### ISSUE TITLE
TET Interface - Response to Language Translations

### ISSUE THREAD

**Issue by eosagie** [routetopa/tet#5]
1. Language translation isn't working when you switch from one language to another except for a few menu list items. The main body of the content of the screen remains in English when you switch from English to other languages
2. 'Join Discussion' button doesn't work - leads to a blank page

**Comment by arekstasiewicz** [comment]
1. translations is ongoing process, as we updating the missing 'strings' once reported
   (see picture). Please note, that the dataset descriptions and the titles will not be translated.
   ![translations](https://cloud.githubusercontent.com/assets/2188771/20304405/efb04514-ab27-11e6-9879-28c7e9ac4135.png)
2. Could you please provide a link to a page with the button. I am not able to reproduce the error: please check i.e. [TET Prato](http://prato-tet.routetopa.eu/en/dataset/05105351-fbaa-4ec7-aee6-f51393bd2863)

**Comment by eosagie** [comment]
I think thes issues are resolved now
