### ISSUE TITLE
RTPA [TET] - file option on the search result view

### ISSUE THREAD

**Issue by eosagie** [routetopa/tet#53]
In the search result view, the options of files (see image) appear greyed out, but they are actually active.
Please make them more visible to users is [possible.]

(http://dublin-tet.routetopa.eu/en/search/?query=Population#)

![image](https://cloud.githubusercontent.com/assets/22979549/23456996/ae582250-fe6d-11e6-9c6f-2ed7aae80744.png)

**Comment by arekstasiewicz** [comment]
it was resolved in #33
