### ISSUE TITLE
Indication of 'Clickable' Text on TET Interface

### ISSUE THREAD

**Issue by eosagie** [routetopa/tet#77]
User comment:
"In the "show more" section in the filters, it would be nice if the cursor showed an arrow"

By the above, the user means: within the text “**_Show more_**” under each filter group in the search result page, the cursor does not change to the or arrow-head shape. The arrow head appears only while touching the the small arrow on the field. User expects the cursor to, in fact, change to the **_finger pointer_** indicating clickable text once cursor enters the text field.
See screen shot: 
![indicate clickable field on search result page](https://user-images.githubusercontent.com/22979549/26971744-7d29c9ee-4d06-11e7-8ff1-e3fd9402f2e2.JPG)

GEt to spot on Dublin TET:
Open Dublin TET (http://dublin-tet.routetopa.eu/en/) -> click on the search button -> view the issue on the left side of the screen

**Comment by arekstasiewicz** [comment]
Identify clickable elements and update CSS
(i.e. show more buttons)

**Comment by MaciejJanowski** [comment]
Done

**Comment by MaciejJanowski** [comment]
Updated css so it should work correctly
